#!/usr/bin/env python3
"""Generate the deterministic responses the mock providers serve.

    python seed/generate_fixtures.py --seed 1337 --out seed/fixtures/responses.jsonl

One record per seeded prompt, with a `frontier` and an `efficient` variant. The gateway looks a
record up by the sha256 of the normalised prompt; anything not found here is synthesised on the
fly by the Go mock, so an interviewer typing an arbitrary curl still gets an answer.

Why two variants rather than one: cost and latency both scale with the number of completion
tokens, so a cheaper model has to produce a visibly shorter answer for the measured cost saving
and the measured latency difference to mean anything. Answer length also scales with difficulty,
because a hard question genuinely costs more to answer than "what is the capital of Peru".

This file is the largest committed artifact (~600 KB). It stays well inside the 5 MB per-file
budget and is regenerated by `make seed`.
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from corpus import estimate_tokens, prompt_key  # noqa: E402

#: Sentence pool for synthetic answers. The text is filler; only its length and determinism
#: matter to the benchmarks, and saying so plainly is better than pretending otherwise.
SENTENCES: tuple[str, ...] = (
    "The short answer is that it depends on the shape of your traffic.",
    "Start by measuring the current behaviour before changing anything.",
    "The dominant cost here is the round trip, not the computation.",
    "There are three failure modes worth planning for, in decreasing order of likelihood.",
    "A bounded queue with explicit backpressure is usually the right default.",
    "Idempotency keys make the retry path safe without coordination.",
    "The trade-off is between tail latency and total throughput.",
    "Instrument the boundary first: you cannot fix what you cannot see.",
    "Prefer a design that fails loudly over one that degrades silently.",
    "This holds as long as writes remain single-writer per partition.",
    "The invariant is that every message is processed at least once.",
    "Under concurrent access the ordering guarantee weakens to per-key.",
    "Batching amortises the fixed cost but raises the worst-case delay.",
    "The simplest correct version is worth writing before the fast one.",
    "Cache invalidation is the part that will bite you six months later.",
    "Set the timeout from the observed p99, not from a round number.",
)

#: Target answer length in sentences, by (tier, difficulty).
#:
#: The frontier model answers more fully; the gap widens with difficulty, which is where the
#: measured quality drift on hard prompts comes from.
LENGTHS: dict[tuple[str, str], tuple[int, int]] = {
    ("frontier", "easy"): (2, 3),
    ("frontier", "medium"): (5, 8),
    ("frontier", "hard"): (9, 14),
    ("efficient", "easy"): (1, 2),
    ("efficient", "medium"): (3, 5),
    ("efficient", "hard"): (4, 6),
}


def build_answer(rng: random.Random, tier: str, difficulty: str) -> str:
    """Compose a deterministic answer of a length appropriate to the tier and difficulty."""
    low, high = LENGTHS[(tier, difficulty)]
    n = rng.randint(low, high)
    # Sample without replacement where possible so an answer does not repeat itself.
    picks = rng.sample(SENTENCES, k=min(n, len(SENTENCES)))
    while len(picks) < n:
        picks.append(rng.choice(SENTENCES))
    return " ".join(picks)


def load_prompts(eval_path: Path, pairs_path: Path) -> list[tuple[str, str]]:
    """Collect every prompt that needs a fixture, as (prompt, difficulty) pairs.

    Both sides of every cache pair need a fixture: the benchmark measures the latency of a
    cache miss on the right-hand prompt, and a miss that fell through to a synthesised answer
    would have a different token count from the one the left-hand prompt cached.
    """
    prompts: dict[str, str] = {}

    if eval_path.exists():
        with eval_path.open(encoding="utf-8") as fh:
            for line in fh:
                if not line.strip():
                    continue
                case = json.loads(line)
                prompts[case["prompt"]] = case["difficulty"]

    if pairs_path.exists():
        with pairs_path.open(encoding="utf-8") as fh:
            for line in fh:
                if not line.strip():
                    continue
                pair = json.loads(line)
                # Cache pairs carry no difficulty label; treat them as medium, which is the
                # middle of the length distribution.
                prompts.setdefault(pair["left"], "medium")
                prompts.setdefault(pair["right"], "medium")

    # Sort for a stable file regardless of dict insertion order.
    return sorted(prompts.items())


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--seed", type=int, default=1337)
    parser.add_argument(
        "--eval", type=Path, default=Path("benchmarks/eval/dataset.jsonl")
    )
    parser.add_argument(
        "--pairs", type=Path, default=Path("benchmarks/cache/pairs.jsonl")
    )
    parser.add_argument(
        "--out", type=Path, default=Path("seed/fixtures/responses.jsonl")
    )
    args = parser.parse_args()

    prompts = load_prompts(args.eval, args.pairs)
    if not prompts:
        print(
            "no source prompts found; run generate_eval_set.py and generate_cache_pairs.py first",
            file=sys.stderr,
        )
        return 1

    rng = random.Random(args.seed + 202)
    records: list[dict[str, Any]] = []

    for prompt, difficulty in prompts:
        variants: dict[str, Any] = {}
        for tier in ("frontier", "efficient"):
            text = build_answer(rng, tier, difficulty)
            variants[tier] = {
                "text": text,
                "completion_tokens": estimate_tokens(text),
                # The frontier variant is the reference answer by construction. The eval
                # harness does not read this field -- it scores against min_quality -- but it
                # documents the intent of the two variants.
                "correct": tier == "frontier",
            }
        records.append(
            {
                "key": prompt_key(prompt),
                "prompt": prompt,
                "difficulty": difficulty,
                "prompt_tokens": estimate_tokens(prompt),
                "responses": variants,
            }
        )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8", newline="\n") as fh:
        for record in records:
            fh.write(json.dumps(record, sort_keys=True, ensure_ascii=False) + "\n")

    size_kb = args.out.stat().st_size / 1024
    print(f"wrote {len(records)} fixtures to {args.out} ({size_kb:.0f} KB)")
    print(f"  seed : {args.seed}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
